# Generated by Django 4.2.15 on 2025-09-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
