# Generated by Django 4.2.15 on 2025-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(blank=True, max_length=500, null=True),
        ),
    ]
