# Generated by Django 4.2.15 on 2025-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
