# Generated by Django 4.2.15 on 2025-07-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companydata", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgquestion",
            name="question_description",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="This description is also visible in the frontend through the question mark icon beside each question when hovered.",
                null=True,
            ),
        ),
    ]
