# Generated by Django 4.2.15 on 2025-07-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companydata", "0003_alter_esgquestion_question_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgresponse",
            name="answer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="esgresponse",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=10,
                null=True,
            ),
        ),
    ]
