# Generated by Django 4.2.15 on 2025-07-20 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "company_photo",
                    models.ImageField(
                        default="/company_default.png",
                        upload_to="",
                        verbose_name="Company Photo",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Terramo Customer", "Terramo Customer")],
                        default="Terramo Customer",
                        max_length=20,
                    ),
                ),
                (
                    "contact_person_first_name",
                    models.CharField(
                        max_length=200, verbose_name="Contact Person First Name"
                    ),
                ),
                (
                    "contact_person_last_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Contact Person Last Name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=8,
                        verbose_name="Gender",
                    ),
                ),
                ("year_of_birth", models.PositiveIntegerField(help_text="YYYY")),
                ("street", models.CharField(max_length=100, verbose_name="Street")),
                ("zip_code", models.CharField(max_length=20, verbose_name="Zip Code")),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                (
                    "landline_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+43 123 456789",
                        max_length=30,
                        region=None,
                        verbose_name="Landline Number",
                    ),
                ),
                (
                    "mobile_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+43 123 1234567",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "land",
                    django_countries.fields.CountryField(
                        default="DE", max_length=2, verbose_name="Land"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "invitation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("miscellaneous", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["company_name", "email"],
            },
        ),
        migrations.CreateModel(
            name="ClientProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchased_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "client_products",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="invited email address"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_accepted", "Not Accepted"),
                            ("accepted", "Accepted (Link Clicked)"),
                            ("registered", "Registered (Account Created)"),
                        ],
                        default="not_accepted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
