# Generated by Django 4.2.15 on 2025-07-16 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clientproduct",
            index=models.Index(
                fields=["client", "is_active"], name="client_prod_client__426010_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientproduct",
            unique_together={("client", "product")},
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["company_name"], name="companies_company_e1b39f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="companies_email_6c1508_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_active"], name="companies_is_acti_e9a12b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("company_name", "land")},
        ),
    ]
