# Generated by Django 4.2.15 on 2025-07-31 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.client"
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("email", "client")},
        ),
        migrations.AddIndex(
            model_name="clientproduct",
            index=models.Index(
                fields=["client", "is_active"], name="client_prod_client__426010_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientproduct",
            unique_together={("client", "product")},
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["company_name"], name="clients_company_570f91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_email_4c8bec_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["is_active"], name="clients_is_acti_43299d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("company_name", "land")},
        ),
    ]
