# Generated by Django 4.2.15 on 2025-09-24 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.client"
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="clientinvitation",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientadmin_invitation",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="clientadminlogintoken",
            name="client_invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="clients.clientinvitation",
                verbose_name="Client Invitation",
            ),
        ),
        migrations.AddField(
            model_name="clientadminlogintoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_login_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="clientadmin",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_admin",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="clientadmin",
            name="invitation_used",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_admin_invitation",
                to="clients.clientinvitation",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("email", "client")},
        ),
        migrations.AddIndex(
            model_name="clientproduct",
            index=models.Index(
                fields=["client", "is_active"], name="client_prod_client__426010_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientproduct",
            unique_together={("client", "product")},
        ),
        migrations.AddIndex(
            model_name="clientadminlogintoken",
            index=models.Index(fields=["token"], name="clients_cli_token_12366d_idx"),
        ),
        migrations.AddIndex(
            model_name="clientadminlogintoken",
            index=models.Index(
                fields=["user", "is_used"], name="clients_cli_user_id_ba558a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientadminlogintoken",
            index=models.Index(
                fields=["expires_at"], name="clients_cli_expires_1e4f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["company_name"], name="clients_company_570f91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_email_4c8bec_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["is_active"], name="clients_is_acti_43299d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("company_name", "land")},
        ),
    ]
