# Generated by Django 4.2.15 on 2025-08-03 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_photo",
            field=models.ImageField(
                default="/company_default.png",
                upload_to="uploads/",
                verbose_name="Company Photo",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=8,
                verbose_name="Gender",
            ),
        ),
        migrations.CreateModel(
            name="ClientInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="Is Email Verified"
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Is Accepted"),
                ),
                ("year", models.PositiveIntegerField(help_text="YYYY")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_invitations",
                        to="clients.client",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Invitation",
                "verbose_name_plural": "Client Invitations",
                "ordering": ["-created_at"],
                "unique_together": {("year", "client")},
            },
        ),
    ]
