# Generated by Django 4.2.15 on 2025-10-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clientadmin",
            index=models.Index(
                fields=["client", "email"], name="clients_cli_client__476092_idx"
            ),
        ),
    ]
