# Generated by Django 4.2.15 on 2025-10-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Männlich", "Männlich"),
                    ("Weiblich", "Weiblich"),
                    ("Divers", "Divers"),
                ],
                default="Männlich",
                max_length=8,
                verbose_name="Gender",
            ),
        ),
    ]
