# Generated by Django 4.2.15 on 2025-07-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["company_name", "email"],
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_company_570f91_idx",
            old_name="companies_company_e1b39f_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_email_4c8bec_idx",
            old_name="companies_email_6c1508_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_is_acti_43299d_idx",
            old_name="companies_is_acti_e9a12b_idx",
        ),
        migrations.AlterModelTable(
            name="client",
            table="clients",
        ),
    ]
