# Generated by Django 4.2.15 on 2025-10-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
    ]
