# Generated by Django 4.2.15 on 2025-08-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_photo_alter_client_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinvitation",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invitation",
                to="clients.client",
            ),
        ),
    ]
