# Generated by Django 4.2.15 on 2025-08-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_clientadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientadmin",
            name="invitation_used",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_admin_invitation",
                to="clients.clientinvitation",
            ),
        ),
    ]
