# Generated by Django 4.2.15 on 2025-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="client",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="client",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Street"),
        ),
    ]
