# Generated by Django 4.2.15 on 2025-08-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_clientinvitation_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinvitation",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientadmin_invitation",
                to="clients.client",
            ),
        ),
    ]
