# Generated by Django 4.2.15 on 2025-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientadmin_invitation_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientadmin",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="clientadmin",
            name="year_of_birth",
        ),
        migrations.AddField(
            model_name="clientinvitation",
            name="days_to_expire",
            field=models.PositiveIntegerField(default=7, verbose_name="Days to Expire"),
        ),
        migrations.AddField(
            model_name="clientinvitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
