# Generated by Django 4.2.15 on 2025-08-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_clientinvitation_client"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientinvitation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="clientinvitation",
            name="year",
        ),
    ]
