# Generated by Django 4.2.15 on 2025-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_remove_clientadmin_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_person_first_name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Contact Person First Name"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_person_last_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Contact Person Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
