# Generated by Django 4.2.15 on 2025-09-11 00:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_client_contact_person_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company_photo_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Company Photo URL"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Company Photo"
            ),
        ),
    ]
