# Generated by Django 4.2.15 on 2025-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_company_photo_url_alter_client_company_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_person_first_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Contact Person First Name",
            ),
        ),
    ]
