# Generated by Django 4.2.15 on 2025-07-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_initial"),
        ("stakeholder_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholderinvitation",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholderinvitation",
            name="stakeholder_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="stakeholder_analysis.stakeholdergroup",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholder_groups",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderinvitation",
            index=models.Index(
                fields=["invite_token"], name="stakeholder_invite__072805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderinvitation",
            index=models.Index(
                fields=["status", "invite_token"], name="stakeholder_status_5ef330_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholderinvitation",
            unique_together={("stakeholder_group", "email")},
        ),
        migrations.AddIndex(
            model_name="stakeholdergroup",
            index=models.Index(
                fields=["client", "is_active"], name="stakeholder_client__439773_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroup",
            index=models.Index(
                fields=["unique_group_token"], name="stakeholder_unique__363de7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholdergroup",
            unique_together={("client", "name")},
        ),
    ]
