# Generated by Django 4.2.15 on 2025-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("terramo_admin", "Terramo Admin"),
                    ("client_admin", "Client Admin"),
                    ("stakeholder", "Stakeholder"),
                ],
                default="stakeholder",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=125, unique=True, verbose_name="Username"
            ),
        ),
    ]
