# Generated by Django 4.2.15 on 2025-07-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("company_admin", "Company Admin"),
                    ("company_user", "Company User"),
                    ("stakeholder", "Stakeholder"),
                ],
                default="company_user",
                max_length=20,
            ),
        ),
    ]
