# Generated by Django 4.2.15 on 2025-08-07 01:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Link"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("account_activation", "Account Activation"),
                            ("two_factor", "Two Factor Authentication"),
                            ("api_access", "API Access"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Token Type",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hashed version of the actual token",
                        max_length=64,
                        unique=True,
                        verbose_name="Token Hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this token expires",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was successfully used",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was revoked",
                        null=True,
                        verbose_name="Revoked At",
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time someone tried to use this token",
                        null=True,
                        verbose_name="Last Attempted At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of times this token was attempted",
                        verbose_name="Attempt Count",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Maximum number of attempts before token is revoked",
                        verbose_name="Max Attempts",
                    ),
                ),
                (
                    "created_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when token was created",
                        null=True,
                        verbose_name="Created IP",
                    ),
                ),
                (
                    "used_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when token was used",
                        null=True,
                        verbose_name="Used IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser user agent when token was used",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data related to this token",
                        verbose_name="Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Token",
                "verbose_name_plural": "Authentication Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientAdmin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("client_admin_invite", "Client Admin Invitation"),
                            ("stakeholder_invite", "Stakeholder Invitation"),
                            ("login_token", "Login Token"),
                        ],
                        max_length=25,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("client_admin", "Client Admin"),
                            ("stakeholder", "Stakeholder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StakeholderGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invitation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "auth_token",
                    models.OneToOneField(
                        limit_choices_to={"token_type": "login"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="authentication.authtoken",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect to after successful login",
                        verbose_name="Redirect URL",
                    ),
                ),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("email_link", "Email Link"),
                            ("sms_link", "SMS Link"),
                            ("qr_code", "QR Code"),
                        ],
                        default="email_link",
                        max_length=20,
                        verbose_name="Login Method",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the device requesting login",
                        verbose_name="Device Info",
                    ),
                ),
                (
                    "location_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Geographic location data when token was created/used",
                        verbose_name="Location Data",
                    ),
                ),
                (
                    "requires_2fa",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this login requires two-factor authentication",
                        verbose_name="Requires 2FA",
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged for suspicious activity",
                        verbose_name="Suspicious Activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Token",
                "verbose_name_plural": "Login Tokens",
            },
        ),
    ]
