# Generated by Django 4.2.15 on 2025-07-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholdergroup",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholder_groups",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.clientadmin",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholders",
                to="authentication.stakeholdergroup",
            ),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="client_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to="authentication.clientadmin",
            ),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="client_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to="authentication.clientadmin",
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="clientadmin",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to="clients.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholdergroup",
            unique_together={("name", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="stakeholder",
            unique_together={("email", "group")},
        ),
    ]
