# Generated by Django 4.2.15 on 2025-08-07 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholdergroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholders",
                to="authentication.stakeholdergroup",
            ),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="client_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to="authentication.clientadmin",
            ),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="client_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to="authentication.clientadmin",
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="clientadmin",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholdergroup",
            unique_together={("name", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="stakeholder",
            unique_together={("email", "group")},
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["user", "token_type"], name="token_user_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["token_type", "is_active"], name="token_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["expires_at", "is_active"], name="token_expires_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(fields=["created_at"], name="token_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="authtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("token_type", "login")),
                fields=("user", "token_type"),
                name="one_active_login_token_per_user",
            ),
        ),
    ]
