# Generated by Django 4.2.15 on 2025-09-24 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholderterramo",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakeholder_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholderlogintoken",
            name="stakeholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="authentication.stakeholder",
                verbose_name="Stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="stakeholderlogintoken",
            name="stakeholder_invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="authentication.stakeholderinvitation",
                verbose_name="Stakeholder Invitation",
            ),
        ),
        migrations.AddField(
            model_name="stakeholderinvitation",
            name="sent_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholderinvitation",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="stakeholderinvitation",
            name="stakeholder_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="authentication.stakeholdergroup",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroupterramo",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for templates",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholder_groups_terramo",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroupterramo",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stakeholder_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroupterramo",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this group was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="authentication.stakeholdergroupterramo",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroupinvitationterramo",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stakeholder_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroupinvitationterramo",
            name="stakeholder_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="authentication.stakeholdergroupterramo",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for templates",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholder_groups",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stakeholderactivitylog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stakeholderactivitylog",
            name="stakeholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="authentication.stakeholderterramo",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Which client this stakeholder belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientstakeholders",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholders",
                to="authentication.stakeholdergroup",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usr_stakeholder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_tokens",
                to="authentication.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["email", "is_active"], name="stakeholder_email_ee86dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["group", "client", "status"],
                name="stakeholder_group_i_5b85c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["client", "is_active"], name="stakeholder_client__2e5535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["is_registered", "is_active"],
                name="stakeholder_is_regi_f75c5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_83fab1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholderterramo",
            constraint=models.UniqueConstraint(
                fields=("email", "group", "client"),
                name="unique_stakeholder_per_group_client",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderlogintoken",
            index=models.Index(fields=["token"], name="authenticat_token_ec86d0_idx"),
        ),
        migrations.AddIndex(
            model_name="stakeholderlogintoken",
            index=models.Index(
                fields=["stakeholder", "is_used"], name="authenticat_stakeho_5e8212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderlogintoken",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_407ff2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholderinvitation",
            unique_together={("email", "stakeholder_group")},
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["client", "is_active"], name="stakeholder_client__ff2d61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["template"], name="stakeholder_templat_1deb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="stakeholder_is_acti_4feb68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_a98721_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholdergroupterramo",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", True), ("template__isnull", True)
                ),
                fields=("name",),
                name="unique_template_terramogroup_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholdergroupterramo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client__isnull", False)),
                fields=("name", "client"),
                name="unique_client_terramo_group_name",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(fields=["token"], name="stakeholder_token_f66113_idx"),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="stakeholder_expires_433be9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["stakeholder_group", "is_active"],
                name="stakeholder_stakeho_2cd569_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_c326a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholdergroup",
            unique_together={("name", "client")},
        ),
        migrations.AddIndex(
            model_name="stakeholderactivitylog",
            index=models.Index(
                fields=["stakeholder", "timestamp"],
                name="stakeholder_stakeho_f345b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderactivitylog",
            index=models.Index(
                fields=["action", "timestamp"], name="stakeholder_action_7dccd2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholder",
            unique_together={("email", "group")},
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["user", "token_type"], name="token_user_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["token_type", "is_active"], name="token_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["expires_at", "is_active"], name="token_expires_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(fields=["created_at"], name="token_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="authtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("token_type", "login")),
                fields=("user", "token_type"),
                name="one_active_login_token_per_user",
            ),
        ),
    ]
