# Generated by Django 4.2.15 on 2025-08-04 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationTokenData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("client_admin_invite", "Client Admin Invitation"),
                            ("stakeholder_invite", "Stakeholder Invitation"),
                            ("login_token", "Login Token"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientadmin_invitation_tokens",
                        to="authentication.clientadmin",
                    ),
                ),
                (
                    "created_by_client_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_created_by_client",
                        to="authentication.clientadmin",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholder_invitation_tokens",
                        to="authentication.stakeholder",
                    ),
                ),
            ],
            options={
                "unique_together": {("token", "token_type")},
            },
        ),
    ]
