# Generated by Django 4.2.15 on 2025-08-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usr_stakeholder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
