# Generated by Django 4.2.15 on 2025-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_stakeholder_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="StakeholderLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_tokens",
                        to="authentication.stakeholder",
                        verbose_name="Stakeholder",
                    ),
                ),
                (
                    "stakeholder_invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_tokens",
                        to="authentication.stakeholderinvitation",
                        verbose_name="Stakeholder Invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stakeholder Login Token",
                "verbose_name_plural": "Stakeholder Login Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="authenticat_token_ec86d0_idx"),
                    models.Index(
                        fields=["stakeholder", "is_used"],
                        name="authenticat_stakeho_5e8212_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_407ff2_idx"
                    ),
                ],
            },
        ),
    ]
