# Generated by Django 4.2.15 on 2025-08-27 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_initial"),
        ("authentication", "0004_stakeholderlogintoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="StakeholderGroupInvitationTerramo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "used_by_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Custom invitation message"),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of uses (0 = unlimited)"
                    ),
                ),
                ("current_uses", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stakeholder_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stakeholder_group_invitation_terramo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderGroupTerramo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for templates",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholder_groups_terramo",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stakeholder_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this group was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="authentication.stakeholdergroupterramo",
                    ),
                ),
            ],
            options={
                "db_table": "stakeholder_group_terramo",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderTerramo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_registered", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invited", "Invited"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("role_in_organization", models.CharField(blank=True, max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Which client this stakeholder belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="clients.client",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="authentication.stakeholdergroupterramo",
                    ),
                ),
                (
                    "invitation_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_stakeholders",
                        to="authentication.stakeholdergroupinvitationterramo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stakeholder_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stakeholder_terramo",
                "ordering": ["last_name", "first_name", "email"],
            },
        ),
        migrations.AddField(
            model_name="stakeholdergroupinvitationterramo",
            name="stakeholder_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="authentication.stakeholdergroupterramo",
            ),
        ),
        migrations.CreateModel(
            name="StakeholderActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="authentication.stakeholderterramo",
                    ),
                ),
            ],
            options={
                "db_table": "stakeholder_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["email", "is_active"], name="stakeholder_email_ee86dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["group", "client", "status"],
                name="stakeholder_group_i_5b85c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["client", "is_active"], name="stakeholder_client__2e5535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["is_registered", "is_active"],
                name="stakeholder_is_regi_f75c5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_83fab1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholderterramo",
            constraint=models.UniqueConstraint(
                fields=("email", "group", "client"),
                name="unique_stakeholder_per_group_client",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["client", "is_active"], name="stakeholder_client__ff2d61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["template"], name="stakeholder_templat_1deb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="stakeholder_is_acti_4feb68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_a98721_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholdergroupterramo",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client__isnull", True), ("template__isnull", True)
                ),
                fields=("name",),
                name="unique_template_terramogroup_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholdergroupterramo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client__isnull", False)),
                fields=("name", "client"),
                name="unique_client_terramo_group_name",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(fields=["token"], name="stakeholder_token_f66113_idx"),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="stakeholder_expires_433be9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["stakeholder_group", "is_active"],
                name="stakeholder_stakeho_2cd569_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdergroupinvitationterramo",
            index=models.Index(
                fields=["created_at"], name="stakeholder_created_c326a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderactivitylog",
            index=models.Index(
                fields=["stakeholder", "timestamp"],
                name="stakeholder_stakeho_f345b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholderactivitylog",
            index=models.Index(
                fields=["action", "timestamp"], name="stakeholder_action_7dccd2_idx"
            ),
        ),
    ]
