# Generated by Django 4.2.15 on 2025-08-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("authentication", "0005_stakeholdergroupinvitationterramo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Which client this stakeholder belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientstakeholders",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
    ]
