# Generated by Django 4.2.15 on 2025-08-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("authentication", "0006_stakeholder_client_stakeholdergroup_is_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholdergroup",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for templates",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stakeholder_groups",
                to="clients.client",
            ),
        ),
    ]
