# Generated by Django 4.2.15 on 2025-08-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_stakeholdergroup_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitationtoken",
            name="client_admin",
        ),
        migrations.RemoveField(
            model_name="loginsession",
            name="client_admin",
        ),
        migrations.DeleteModel(
            name="ClientAdmin",
        ),
    ]
