# Generated by Django 4.2.15 on 2025-08-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_remove_invitationtoken_client_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholdergroupinvitationterramo",
            name="days_to_expire",
            field=models.PositiveIntegerField(default=7, verbose_name="Days to Expire"),
        ),
        migrations.AlterField(
            model_name="stakeholdergroupinvitationterramo",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
