# Generated by Django 4.2.15 on 2025-09-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0009_stakeholdergroupinvitationterramo_days_to_expire_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stakeholdergroup",
            options={"ordering": ["-is_global", "-name"]},
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stakeholdergroup",
            name="disable_the_invitation",
            field=models.BooleanField(
                default=False, verbose_name="Disable the Invitaion"
            ),
        ),
    ]
