# Generated by Django 4.2.15 on 2025-09-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0010_alter_stakeholdergroup_options_stakeholder_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholdergroup",
            name="show_in_table",
            field=models.BooleanField(default=False),
        ),
    ]
