# Generated by Django 4.2.15 on 2025-09-24 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "Low Priority"),
                            (2, "Medium Priority"),
                            (3, "High Priority"),
                            (4, "Very High Priority"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "status_quo",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Excellent"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Client Responses",
                "db_table": "client_responses",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ESGAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("environment_priority_avg", models.FloatField(default=0.0)),
                ("environment_status_quo_avg", models.FloatField(default=0.0)),
                ("social_priority_avg", models.FloatField(default=0.0)),
                ("social_status_quo_avg", models.FloatField(default=0.0)),
                ("governance_priority_avg", models.FloatField(default=0.0)),
                ("governance_status_quo_avg", models.FloatField(default=0.0)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "ESG Analytics",
                "db_table": "esg_analytics",
            },
        ),
        migrations.CreateModel(
            name="ESGCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "ESG Categories",
                "db_table": "esg_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ESGQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measure", models.TextField()),
                ("index_code", models.CharField(max_length=10)),
                ("desription", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "ESG Questions",
                "db_table": "esg_questions",
                "ordering": ["category", "order", "index_code"],
            },
        ),
        migrations.CreateModel(
            name="ESGQuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire_type",
                    models.CharField(
                        choices=[
                            ("client_admin", "Client Admin"),
                            ("stakeholder", "Stakeholder"),
                        ],
                        default="stakeholder",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "Not Started"),
                            (1, "Low Priority"),
                            (2, "Medium Priority"),
                            (3, "High Priority"),
                            (4, "Very High Priority"),
                        ],
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "status_quo",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "Not Started"),
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Excellent"),
                        ],
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "ESGQuestion Responses",
                "db_table": "esg_question_responses",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ESGSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="ESG-Check", max_length=200)),
                ("year", models.PositiveIntegerField(default=2025)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esg_surveys",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ESG Surveys",
                "db_table": "esg_surveys",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ESGSurveyQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esg.esgquestion",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_questions",
                        to="esg.esgsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ESG Survey Questions",
                "db_table": "esg_survey_questions",
                "ordering": ["survey", "question__category", "order"],
            },
        ),
        migrations.CreateModel(
            name="ESGYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2020)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "esg_years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "Low Priority"),
                            (2, "Medium Priority"),
                            (3, "High Priority"),
                            (4, "Very High Priority"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "status_quo",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Excellent"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esg_responses",
                        to="authentication.stakeholder",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="esg.esgsurvey",
                    ),
                ),
                (
                    "survey_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esg.esgsurveyquestion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stakeholder Responses",
                "db_table": "stakeholder_responses",
                "ordering": ["-updated_at"],
            },
        ),
    ]
