# Generated by Django 4.2.15 on 2025-07-16 01:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ESGAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("reorder", "Reorder"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "esg_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ESGCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("E", "Environment"),
                            ("S", "Social"),
                            ("G", "Corporate Governance"),
                        ],
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ESG Category",
                "verbose_name_plural": "ESG Categories",
                "db_table": "esg_categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ESGQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measure_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("measure", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status_quo",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "esg_questions",
                "ordering": ["category", "year", "order"],
            },
        ),
        migrations.CreateModel(
            name="ESGResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status_quo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_draft", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "esg_responses",
            },
        ),
        migrations.CreateModel(
            name="ESGYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2020)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "esg_years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="ESGSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("completed_questions", models.PositiveIntegerField(default=0)),
                ("in_progress_questions", models.PositiveIntegerField(default=0)),
                ("not_started_questions", models.PositiveIntegerField(default=0)),
                ("high_priority_count", models.PositiveIntegerField(default=0)),
                ("medium_priority_count", models.PositiveIntegerField(default=0)),
                ("low_priority_count", models.PositiveIntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="esg.esgcategory",
                    ),
                ),
            ],
            options={
                "db_table": "esg_summaries",
            },
        ),
    ]
