# Generated by Django 4.2.15 on 2025-07-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("esg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="esgsummary",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgsummary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgsummary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esg_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgsummary",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="esg.esgyear",
            ),
        ),
        migrations.AddField(
            model_name="esgresponse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="esg.esgquestion",
            ),
        ),
        migrations.AddField(
            model_name="esgresponse",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_esg_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="esg.esgcategory",
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="esg.esgyear",
            ),
        ),
        migrations.AddField(
            model_name="esgcategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgcategory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="esg_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="esgsummary",
            index=models.Index(
                fields=["user", "year"], name="esg_summari_user_id_78ac9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esgsummary",
            index=models.Index(
                fields=["year", "category"], name="esg_summari_year_id_d5550d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="esgsummary",
            unique_together={("user", "year", "category")},
        ),
        migrations.AddIndex(
            model_name="esgresponse",
            index=models.Index(
                fields=["user", "question"], name="esg_respons_user_id_bc2e80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esgresponse",
            index=models.Index(
                fields=["question", "is_draft"], name="esg_respons_questio_a75a85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="esgresponse",
            unique_together={("question", "user")},
        ),
        migrations.AddIndex(
            model_name="esgquestion",
            index=models.Index(
                fields=["category", "year"], name="esg_questio_categor_1b5b70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esgquestion",
            index=models.Index(
                fields=["measure_id"], name="esg_questio_measure_585086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esgquestion",
            index=models.Index(
                fields=["year", "is_active"], name="esg_questio_year_id_df76b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="esgquestion",
            unique_together={("category", "year", "order")},
        ),
        migrations.AddIndex(
            model_name="esgauditlog",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="esg_audit_l_model_n_169f69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="esgauditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="esg_audit_l_user_id_ded37f_idx"
            ),
        ),
    ]
