# Generated by Django 4.2.15 on 2025-08-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="esgquestion",
            name="questionnaire_type",
        ),
    ]
