# Generated by Django 4.2.15 on 2025-10-07 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esg", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="esgsurvey",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="esgquestionresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="esg.esgquestion",
            ),
        ),
        migrations.AddField(
            model_name="esgquestionresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_esg_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="esg.esgcategory",
            ),
        ),
        migrations.AddField(
            model_name="esgquestion",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="year_questions",
                to="esg.esgyear",
            ),
        ),
        migrations.AddField(
            model_name="esganalytics",
            name="survey",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="esg.esgsurvey",
            ),
        ),
        migrations.AddField(
            model_name="clientresponse",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_responses",
                to="esg.esgsurvey",
            ),
        ),
        migrations.AddField(
            model_name="clientresponse",
            name="survey_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="esg.esgsurveyquestion"
            ),
        ),
        migrations.AddField(
            model_name="clientresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stakeholderresponse",
            unique_together={("survey", "stakeholder", "survey_question")},
        ),
        migrations.AlterUniqueTogether(
            name="esgsurveyquestion",
            unique_together={("survey", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="esgsurvey",
            unique_together={("client", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="esgquestionresponse",
            unique_together={("question", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="esgquestion",
            unique_together={("category", "index_code")},
        ),
        migrations.AlterUniqueTogether(
            name="clientresponse",
            unique_together={("survey", "user", "survey_question")},
        ),
    ]
