# Generated by Django 4.2.15 on 2025-10-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="esgcategory",
            name="category_prefix",
            field=models.CharField(default="E", max_length=1),
        ),
    ]
