# Generated by Django 4.2.15 on 2025-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0002_remove_esgquestion_questionnaire_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="esgquestion",
            name="desription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="esgquestionresponse",
            name="questionnaire_type",
            field=models.CharField(
                choices=[
                    ("client_admin", "Client Admin"),
                    ("stakeholder", "Stakeholder"),
                ],
                default="stakeholder",
                max_length=20,
            ),
        ),
    ]
