# Generated by Django 4.2.15 on 2025-07-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="esgresponse",
            name="client",
        ),
    ]
