# Generated by Django 4.2.15 on 2025-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0003_esgcategory_category_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgcategory",
            name="category_prefix",
            field=models.CharField(max_length=1),
        ),
    ]
