# Generated by Django 4.2.15 on 2025-08-13 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esg", "0003_esgquestion_desription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgquestionresponse",
            name="priority",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "Not Started"),
                    (1, "Low Priority"),
                    (2, "Medium Priority"),
                    (3, "High Priority"),
                    (4, "Very High Priority"),
                ],
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="esgquestionresponse",
            name="status_quo",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "Not Started"),
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Excellent"),
                ],
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
