# Generated by Django 4.2.15 on 2025-09-29 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("authentication", "0003_initial"),
        ("esg", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleMaterialityStakeholders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_included", models.BooleanField(default=False)),
                (
                    "weighting",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_stakehoders_client",
                        to="clients.client",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_stakehoders_stakeholder",
                        to="authentication.stakeholder",
                    ),
                ),
            ],
            options={
                "ordering": ["client"],
                "indexes": [
                    models.Index(
                        fields=["client"], name="double_mate_client__5c6ea0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoubleMaterialitySelectionIROAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "punkte_rt",
                    models.PositiveIntegerField(
                        default=None,
                        help_text="Score RT ( Choose from 1 to 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "punkte_sh",
                    models.PositiveIntegerField(
                        default=None,
                        help_text="Score SH ( Choose from 1 to 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("relevant", models.BooleanField(default=False)),
                (
                    "justification",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_selection_iro_assessment_client",
                        to="clients.client",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_selection_iro_assessment_question",
                        to="esg.esgquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["client"],
                "indexes": [
                    models.Index(
                        fields=["client"], name="double_mate_client__4a8926_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoubleMaterialityIROAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("punkte", models.FloatField(help_text="Punkte or Score")),
                (
                    "impact",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Impact ( Choose from 1 to 10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "risk",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Risk ( Choose from 1 to 10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "chance",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Chance ( Choose from 1 to 10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("has_report", models.BooleanField(default=False)),
                (
                    "justification",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_iro_assessment_client",
                        to="clients.client",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doublemateriality_iro_assessment_question",
                        to="esg.esgquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["client"],
                "indexes": [
                    models.Index(
                        fields=["client"], name="double_mate_client__bf17f9_idx"
                    )
                ],
            },
        ),
    ]
