# Generated by Django 4.2.15 on 2025-10-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esg", "0001_initial"),
        ("double_materiality", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublematerialityselectioniroassessment",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doublemateriality_selection_iro_assessment_question",
                to="esg.esgquestion",
            ),
        ),
        migrations.AddField(
            model_name="doublematerialityiroassessment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doublemateriality_iro_assessment_client",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="doublematerialityiroassessment",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doublemateriality_iro_assessment_question",
                to="esg.esgquestion",
            ),
        ),
        migrations.AddIndex(
            model_name="doublematerialitystakeholders",
            index=models.Index(
                fields=["client"], name="double_mate_client__5c6ea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doublematerialityselectioniroassessment",
            index=models.Index(
                fields=["client"], name="double_mate_client__4a8926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doublematerialityiroassessment",
            index=models.Index(
                fields=["client"], name="double_mate_client__bf17f9_idx"
            ),
        ),
    ]
